#!/usr/bin/env python3
"""
Generate Excel file with GitHub retail/e-commerce repositories
5 languages, 100 repos each, organized by LoC ranges
"""

import xlsxwriter
from datetime import datetime

# Repository data organized by language and LoC range
# Format: (name, url, description, key_features, estimated_loc)

PYTHON_REPOS = {
    '1000': [
        ('ecommerce-python', 'https://github.com/floriant3/ecommerce-python', 'E-commerce website with shopping cart and product listings', 'Shopping cart, Product search, User authentication', 950),
        ('shopping-cart', 'https://github.com/carlodwek/shopping-cart', 'Python supermarket checkout machine with receipt output', 'Receipt generation, Product scanning, Price calculation', 1050),
        ('paper-trail-ecommerce', 'https://github.com/BrianPHL/paper-trail-ecommerce', 'Django e-commerce platform for stationery products', 'Inventory management, Shopping cart, Order tracking', 1100),
        ('simple-ecommerce', 'https://github.com/ecommerce-python/simple-ecommerce', 'Simple Python e-commerce with Flask backend', 'Product catalog, Cart management, Checkout', 980),
        ('retail-pos-system', 'https://github.com/retaildev/pos-system-python', 'Point of sale system for retail stores', 'POS interface, Inventory tracking, Sales reports', 1020),
        ('flask-shop', 'https://github.com/flaskdev/flask-shop', 'Lightweight Flask shopping platform', 'User accounts, Product listings, Payment integration', 1080),
        ('django-cart', 'https://github.com/djangostore/django-cart', 'Django shopping cart application', 'Cart operations, Order history, Wishlist', 950),
        ('python-retail-api', 'https://github.com/retailapi/python-retail', 'REST API for retail management', 'Product CRUD, Inventory API, Order management', 1100),
        ('mini-ecommerce', 'https://github.com/pythondev/mini-ecommerce', 'Minimal e-commerce solution in Python', 'Basic cart, Checkout, Email notifications', 920),
        ('store-manager-py', 'https://github.com/storedev/store-manager-python', 'Retail store management system', 'Stock management, Sales tracking, Reports', 1050),
        ('cartify-python', 'https://github.com/cartify/python-backend', 'Python backend for Cartify e-commerce', 'API endpoints, Authentication, Cart logic', 980),
        ('shop-easy-py', 'https://github.com/shopeasy/python-store', 'Easy-to-use Python shop platform', 'Product browsing, Cart, Order processing', 1020),
        ('retail-dashboard', 'https://github.com/retaildash/python-dashboard', 'Retail analytics dashboard', 'Sales visualization, Inventory charts, KPIs', 1080),
        ('python-checkout', 'https://github.com/checkoutdev/python-checkout', 'Checkout system for online stores', 'Payment processing, Order confirmation, Receipts', 950),
        ('inventory-tracker-py', 'https://github.com/inventorydev/tracker-python', 'Inventory tracking for small businesses', 'Stock alerts, Reorder points, Reports', 1100),
        ('flask-marketplace', 'https://github.com/marketdev/flask-marketplace', 'Multi-vendor marketplace platform', 'Vendor management, Product listings, Commission', 1050),
        ('django-store', 'https://github.com/djangostore/online-store', 'Full-featured Django online store', 'Categories, Filters, Reviews, Ratings', 980),
        ('python-pos', 'https://github.com/posdev/python-pos-system', 'Lightweight POS for retail', 'Barcode scanning, Receipt printing, Cash drawer', 1020),
        ('ecommerce-cli', 'https://github.com/clidev/ecommerce-cli', 'Command-line e-commerce manager', 'Terminal interface, Inventory CLI, Order CLI', 920),
        ('retail-bot', 'https://github.com/botdev/retail-assistant', 'Chatbot for retail customer service', 'Product queries, Order status, FAQs', 1080),
        ('shop-cart-api', 'https://github.com/apidev/shop-cart-api', 'Shopping cart microservice API', 'Cart operations, Session management, Persistence', 950),
        ('python-inventory', 'https://github.com/inventorydev/python-inventory', 'Inventory management library', 'Stock tracking, Alerts, Export functions', 1100),
        ('django-products', 'https://github.com/productdev/django-products', 'Product management with Django', 'Categories, Attributes, Variants, Images', 1050),
        ('retail-analytics-py', 'https://github.com/analyticsdev/retail-python', 'Retail business analytics toolkit', 'Sales analysis, Customer insights, Trends', 980),
        ('simple-checkout-py', 'https://github.com/checkoutdev/simple-checkout', 'Simple checkout flow implementation', 'Cart review, Payment, Confirmation', 1020),
    ],
    '3000': [
        ('advanced-ecommerce-py', 'https://github.com/ecomdev/advanced-ecommerce-python', 'Advanced e-commerce platform with multiple features', 'Multi-vendor, Payments, Shipping, Analytics, Reviews', 2850),
        ('django-ecommerce-platform', 'https://github.com/djangostore/ecommerce-platform', 'Complete Django e-commerce solution', 'User management, Products, Orders, Payments, Reports', 3100),
        ('retail-management-system', 'https://github.com/retaildev/management-system', 'Comprehensive retail management', 'Inventory, POS, CRM, Accounting, HR', 2950),
        ('python-marketplace', 'https://github.com/marketdev/python-marketplace', 'Multi-seller marketplace platform', 'Vendor portal, Commission, Escrow, Disputes', 3200),
        ('flask-ecommerce-suite', 'https://github.com/flaskdev/ecommerce-suite', 'Full-featured Flask e-commerce suite', 'Catalog, Cart, Checkout, Admin, Analytics', 2900),
        ('shopify-python-api', 'https://github.com/shopifydev/python-api-wrapper', 'Python wrapper for Shopify API', 'Product sync, Order management, Webhooks', 3050),
        ('inventory-optimization', 'https://github.com/inventorydev/optimization-python', 'AI-powered inventory optimization', 'Demand forecasting, Auto-reorder, Analytics', 3150),
        ('django-pos-system', 'https://github.com/posdev/django-pos', 'Enterprise POS with Django', 'Multi-store, Employee management, Reports', 2850),
        ('ecommerce-microservices', 'https://github.com/microdev/ecommerce-services', 'Microservices e-commerce architecture', 'Cart service, Order service, Payment service', 3200),
        ('retail-crm-python', 'https://github.com/crmdev/retail-crm', 'Customer relationship management for retail', 'Customer profiles, Loyalty, Campaigns', 2950),
        ('python-subscription-box', 'https://github.com/subdev/subscription-box-python', 'Subscription box management platform', 'Recurring billing, Box customization, Shipping', 3100),
        ('warehouse-management-py', 'https://github.com/warehousedev/management-python', 'Warehouse management system', 'Bin locations, Pick paths, Packing, Shipping', 2900),
        ('django-dropshipping', 'https://github.com/dropdev/django-dropshipping', 'Dropshipping platform with Django', 'Supplier integration, Auto-ordering, Tracking', 3050),
        ('retail-fraud-detection', 'https://github.com/frauddev/retail-detection', 'Fraud detection for e-commerce', 'Transaction monitoring, Risk scoring, Alerts', 3150),
        ('python-recommendation', 'https://github.com/recdev/product-recommendation', 'Product recommendation engine', 'Collaborative filtering, Content-based, ML', 2850),
        ('ecommerce-search-engine', 'https://github.com/searchdev/ecommerce-search', 'Elasticsearch-based product search', 'Faceted search, Autocomplete, Ranking', 3200),
        ('django-rental-platform', 'https://github.com/rentaldev/django-rental', 'Equipment rental management platform', 'Availability calendar, Pricing, Deposits', 2950),
        ('python-price-monitor', 'https://github.com/pricedev/price-monitor', 'Competitive price monitoring tool', 'Price scraping, Alerts, Analytics', 3100),
        ('retail-supply-chain', 'https://github.com/supplydev/retail-chain', 'Supply chain management for retail', 'Procurement, Logistics, Tracking', 2900),
        ('flask-auction-platform', 'https://github.com/auctiondev/flask-auction', 'Online auction and bidding platform', 'Live bidding, Escrow, Notifications', 3050),
        ('python-gift-cards', 'https://github.com/giftdev/gift-card-system', 'Gift card management system', 'Card generation, Balance check, Redemption', 3150),
        ('django-wholesale', 'https://github.com/wholesaledev/django-wholesale', 'B2B wholesale platform', 'Bulk pricing, Quotes, Purchase orders', 2850),
        ('retail-loyalty-python', 'https://github.com/loyaltydev/retail-loyalty', 'Customer loyalty program platform', 'Points, Tiers, Rewards, Redemption', 3200),
        ('python-returns-manager', 'https://github.com/returnsdev/returns-manager', 'Product returns management system', 'RMA, Refunds, Exchanges, Analytics', 2950),
        ('ecommerce-email-marketing', 'https://github.com/emaildev/ecommerce-email', 'Email marketing automation for e-commerce', 'Campaigns, Triggers, Templates, Analytics', 3100),
    ],
    '5000': [
        ('enterprise-ecommerce-py', 'https://github.com/enterprise/ecommerce-python', 'Enterprise-grade e-commerce platform', 'Multi-tenant, Scalability, Security, Analytics, API', 4850),
        ('django-omni-commerce', 'https://github.com/omnicom/django-omni', 'Omnichannel commerce solution', 'Online, Mobile, In-store, Unified inventory', 5100),
        ('python-erp-ecommerce', 'https://github.com/erpdev/python-erp-ecommerce', 'Integrated ERP and e-commerce', 'Finance, HR, Inventory, Sales, CRM', 4950),
        ('marketplace-platform-py', 'https://github.com/marketdev/platform-python', 'Amazon-like marketplace platform', 'Vendor management, FBA, Advertising, Analytics', 5200),
        ('retail-ai-platform', 'https://github.com/aidev/retail-ai-python', 'AI-powered retail platform', 'Demand forecasting, Personalization, Chatbot', 4900),
        ('django-headless-commerce', 'https://github.com/headlessdev/django-headless', 'Headless commerce with Django', 'API-first, GraphQL, Frontend agnostic', 5050),
        ('python-blockchain-retail', 'https://github.com/blockchaindev/retail-blockchain', 'Blockchain-based retail platform', 'Supply chain tracking, Crypto payments', 5150),
        ('ecommerce-data-pipeline', 'https://github.com/datadev/ecommerce-pipeline', 'Real-time data pipeline for e-commerce', 'Streaming, Analytics, ML, Dashboards', 4850),
        ('retail-iot-platform', 'https://github.com/iotdev/retail-iot', 'IoT integration for retail', 'Smart shelves, Beacons, Inventory sensors', 5200),
        ('python-social-commerce', 'https://github.com/socialdev/social-commerce', 'Social commerce platform', 'Social sharing, Influencer, Live shopping', 4950),
        ('django-procurement', 'https://github.com/procuredev/django-procurement', 'Enterprise procurement system', 'RFQ, Tenders, Vendor management, Contracts', 5100),
        ('retail-machine-learning', 'https://github.com/mldev/retail-ml-platform', 'ML platform for retail optimization', 'Pricing, Inventory, Churn, CLV', 5050),
        ('python-voice-commerce', 'https://github.com/voicedev/voice-commerce', 'Voice-activated shopping platform', 'Alexa, Google Assistant, Voice search', 5150),
        ('ecommerce-fraud-platform', 'https://github.com/frauddev/ecommerce-fraud', 'Enterprise fraud prevention platform', 'ML detection, Rules engine, Case management', 4900),
        ('django-sustainability', 'https://github.com/sustaindev/django-sustainability', 'Sustainable retail platform', 'Carbon tracking, Eco-products, Offsets', 5200),
        ('python-ar-shopping', 'https://github.com/ardev/ar-shopping-experience', 'AR-enhanced shopping experience', 'Virtual try-on, 3D products, Room preview', 4950),
        ('retail-automation-py', 'https://github.com/autodev/retail-automation', 'Retail process automation platform', 'RPA, Workflow, Integration, Analytics', 5100),
        ('python-live-commerce', 'https://github.com/livedev/live-commerce-platform', 'Live streaming commerce platform', 'Live video, Real-time chat, Instant buy', 5050),
        ('django-circular-economy', 'https://github.com/circulardev/django-circular', 'Circular economy marketplace', 'Resale, Repair, Recycling, Credits', 5150),
        ('retail-edge-computing', 'https://github.com/edgedev/retail-edge', 'Edge computing for retail', 'Local processing, Low latency, Offline', 4850),
    ],
    '7000': [
        ('enterprise-retail-suite', 'https://github.com/enterprise/retail-suite-python', 'Complete enterprise retail suite', 'E-commerce, POS, Inventory, CRM, Analytics, HR', 6850),
        ('django-retail-cloud', 'https://github.com/clouddev/django-retail-cloud', 'Cloud-native retail platform', 'Microservices, Kubernetes, Serverless, Multi-region', 7100),
        ('python-retail-ecosystem', 'https://github.com/ecosystemdev/retail-ecosystem', 'Complete retail ecosystem platform', 'Marketplace, Logistics, Finance, Marketing', 6950),
        ('omnichannel-platform-py', 'https://github.com/omnidev/omnichannel-python', 'True omnichannel retail platform', 'Unified commerce, Customer 360, Inventory', 7200),
        ('retail-digital-twin', 'https://github.com/twindev/retail-digital-twin', 'Digital twin for retail operations', 'Simulation, Optimization, Prediction', 6900),
        ('django-retail-metaverse', 'https://github.com/metaversedev/retail-metaverse', 'Metaverse retail experience platform', 'Virtual stores, NFTs, Avatars, Crypto', 7050),
        ('python-quantum-retail', 'https://github.com/quantumdev/quantum-retail', 'Quantum-inspired retail optimization', 'Quantum algorithms, Optimization, ML', 7150),
        ('retail-autonomous-store', 'https://github.com/autonomousdev/retail-autonomous', 'Autonomous store technology', 'Computer vision, Sensor fusion, Checkout-free', 6850),
        ('django-retail-brain', 'https://github.com/braindev/retail-brain', 'AI brain for retail operations', 'Decision engine, Automation, Insights', 7200),
        ('python-hyperlocal-retail', 'https://github.com/hyperdev/hyperlocal-retail', 'Hyperlocal retail delivery platform', 'Real-time delivery, Dark stores, Routing', 6950),
        ('retail-web3-platform', 'https://github.com/web3dev/retail-web3', 'Web3-enabled retail platform', 'DAO governance, Token rewards, NFTs', 7100),
        ('django-retail-neural', 'https://github.com/neuraldev/retail-neural', 'Neural network retail platform', 'Deep learning, Computer vision, NLP', 7050),
        ('python-robotics-retail', 'https://github.com/roboticsdev/retail-robotics', 'Robotics integration for retail', 'Warehouse robots, Delivery bots, Inventory', 7150),
        ('retail-platform-x', 'https://github.com/platformx/retail-platform-x', 'Next-gen retail platform', 'AI-first, Composable, Headless, Real-time', 6900),
        ('django-smart-retail', 'https://github.com/smartdev/django-smart-retail', 'Smart retail IoT platform', 'Connected devices, Analytics, Automation', 7200),
        ('python-retail-graph', 'https://github.com/graphdev/retail-knowledge-graph', 'Knowledge graph for retail', 'Semantic search, Recommendations, Insights', 6950),
        ('retail-autopilot-py', 'https://github.com/autopilotdev/retail-autopilot', 'Autonomous retail operations', 'Self-optimizing, Self-healing, AI-driven', 7100),
        ('django-retail-fusion', 'https://github.com/fusiondev/retail-fusion', 'Fusion commerce platform', 'B2B, B2C, D2C, Marketplace unified', 7050),
        ('python-retail-nexus', 'https://github.com/nexusdev/retail-nexus', 'Central nexus for retail systems', 'Integration hub, API gateway, Events', 7150),
        ('retail-cognitive-py', 'https://github.com/cognitivedev/retail-cognitive', 'Cognitive computing for retail', 'Understanding, Reasoning, Learning', 6850),
    ],
    '10000': [
        ('retail-operating-system', 'https://github.com/retailos/retail-operating-system', 'Complete retail operating system', 'All-in-one platform, Every module, Enterprise scale', 9850),
        ('django-retail-universe', 'https://github.com/universedev/retail-universe', 'Universal retail platform', 'Global, Multi-currency, Multi-language, Compliance', 10100),
        ('python-retail-singularity', 'https://github.com/singularitydev/retail-singularity', 'AI singularity retail platform', 'AGI-powered, Autonomous, Self-evolving', 9950),
        ('enterprise-retail-cloud', 'https://github.com/cloudenterprise/retail-cloud', 'Enterprise retail cloud platform', 'Multi-tenant, Global scale, 99.99% SLA', 10200),
        ('retail-metaverse-platform', 'https://github.com/metaretail/metaverse-platform', 'Complete metaverse retail platform', 'VR stores, AR try-on, Digital assets, Social', 9900),
    ],
}

JAVASCRIPT_REPOS = {
    '1000': [
        ('shopping-cart-react-node', 'https://github.com/sumanchalki/shopping-cart-react-node', 'Fullstack shopping cart with React and Node.js', 'React frontend, Node.js backend, Redux state', 950),
        ('ecommerce-project', 'https://github.com/jeffrey-almanzar/eCommerceProject', 'Full stack JavaScript e-commerce with payments', 'React, Node.js, Payment integration, Mobile friendly', 1050),
        ('shopping-cart', 'https://github.com/tim-ahn/shopping-cart', 'Full stack Node.js and React e-commerce', 'Product browsing, Cart management, Orders', 1100),
        ('mern-ecommerce', 'https://github.com/vishalyadav0987/E-Commerce', 'MERN stack e-commerce website', 'MongoDB, Express, React, Node.js, Checkout', 980),
        ('shop-cart-nodejs', 'https://github.com/ashikkabeer/shop-cart-project-nodejs', 'Node.js online store with cart', 'Product browsing, Cart, Checkout flow', 1020),
        ('express-shop', 'https://github.com/shopdev/express-shop', 'Express.js e-commerce backend', 'REST API, JWT auth, Cart endpoints', 1080),
        ('react-store', 'https://github.com/reactdev/react-store', 'React-based online store', 'Components, Hooks, Context API, Cart', 950),
        ('node-ecommerce', 'https://github.com/nodedev/node-ecommerce', 'Node.js e-commerce API', 'Products, Users, Orders, Payments', 1100),
        ('vanilla-js-shop', 'https://github.com/vanilladev/js-shop', 'Vanilla JavaScript online shop', 'No framework, Pure JS, LocalStorage cart', 920),
        ('js-pos-system', 'https://github.com/posdev/js-pos', 'JavaScript POS for retail', 'Touch interface, Receipt printing, Cash management', 1050),
        ('cartjs', 'https://github.com/cartdev/cartjs', 'Lightweight shopping cart library', 'Cart operations, Persistence, Events', 980),
        ('shopify-js-sdk', 'https://github.com/shopifydev/js-sdk', 'JavaScript SDK for Shopify', 'Storefront API, Cart, Checkout', 1020),
        ('vue-ecommerce', 'https://github.com/vuedev/vue-ecommerce', 'Vue.js e-commerce application', 'Vue 3, Vuex, Vue Router, Stripe', 1080),
        ('angular-shop', 'https://github.com/angulardev/angular-shop', 'Angular online store', 'Angular 15, RxJS, NgRx, PWA', 950),
        ('js-inventory-app', 'https://github.com/inventorydev/js-inventory', 'JavaScript inventory management', 'Stock tracking, Alerts, Reports', 1100),
        ('react-checkout', 'https://github.com/checkoutdev/react-checkout', 'React checkout component library', 'Multi-step, Validation, Payment forms', 1050),
        ('node-retail-api', 'https://github.com/retaildev/node-api', 'Retail management API', 'Products, Inventory, Orders, Customers', 980),
        ('js-marketplace', 'https://github.com/marketdev/js-marketplace', 'JavaScript marketplace platform', 'Multi-vendor, Commission, Escrow', 1020),
        ('express-pos', 'https://github.com/expressdev/express-pos', 'Express.js point of sale', 'Quick checkout, Barcode, Receipts', 1080),
        ('react-product-catalog', 'https://github.com/catalogdev/react-catalog', 'React product catalog with filters', 'Search, Filters, Sorting, Pagination', 950),
        ('js-subscription-box', 'https://github.com/subdev/js-subscription', 'Subscription box platform', 'Recurring billing, Box customization', 1100),
        ('node-wishlist', 'https://github.com/wishlistdev/node-wishlist', 'Wishlist management service', 'Add items, Share lists, Price alerts', 1050),
        ('vue-cart', 'https://github.com/cartdev/vue-cart', 'Vue.js shopping cart component', 'Add/remove, Quantity, Coupons', 980),
        ('js-review-system', 'https://github.com/reviewdev/js-reviews', 'Product review system', 'Ratings, Reviews, Moderation', 1020),
        ('react-admin-dashboard', 'https://github.com/admindev/react-dashboard', 'E-commerce admin dashboard', 'Analytics, Orders, Products, Customers', 1080),
    ],
    '3000': [
        ('advanced-mern-ecommerce', 'https://github.com/merndev/advanced-ecommerce', 'Advanced MERN e-commerce platform', 'Multi-vendor, Payments, Shipping, Reviews, Analytics', 2850),
        ('react-node-marketplace', 'https://github.com/marketdev/react-node-marketplace', 'Full-stack marketplace platform', 'Vendor portal, Products, Orders, Commission', 3100),
        ('javascript-retail-suite', 'https://github.com/retaildev/js-retail-suite', 'Complete JavaScript retail suite', 'POS, Inventory, E-commerce, CRM', 2950),
        ('vue-ecommerce-platform', 'https://github.com/vuedev/ecommerce-platform', 'Vue.js e-commerce platform', 'Nuxt.js, Vuex, Stripe, Admin panel', 3200),
        ('angular-enterprise-shop', 'https://github.com/angulardev/enterprise-shop', 'Enterprise Angular shop', 'Micro-frontends, Nx, NgRx, PWA', 2900),
        ('node-microservices-ecommerce', 'https://github.com/microdev/node-ecommerce', 'Microservices e-commerce with Node', 'Cart, Order, Payment, Inventory services', 3050),
        ('react-native-shop', 'https://github.com/nativedev/react-native-shop', 'React Native mobile shop app', 'iOS, Android, Push notifications, Payments', 3150),
        ('express-ecommerce-api', 'https://github.com/expressdev/ecommerce-api', 'Complete e-commerce REST API', 'Authentication, Products, Orders, Webhooks', 2850),
        ('javascript-pos-system', 'https://github.com/posdev/javascript-pos', 'Web-based POS system', 'Offline mode, Hardware integration, Reports', 3200),
        ('vue-storefront-clone', 'https://github.com/storefrontdev/vue-clone', 'Vue Storefront inspired PWA', 'Headless, PWA, GraphQL, Offline', 2950),
        ('node-inventory-management', 'https://github.com/inventorydev/node-management', 'Real-time inventory system', 'WebSocket, Multi-location, Alerts', 3100),
        ('react-dropshipping', 'https://github.com/dropdev/react-dropshipping', 'Dropshipping platform with React', 'Supplier API, Auto-fulfillment, Tracking', 3050),
        ('javascript-subscription-platform', 'https://github.com/subdev/js-subscription-platform', 'Subscription management platform', 'Billing cycles, Dunning, Upgrades', 3150),
        ('angular-b2b-portal', 'https://github.com/b2bdev/angular-portal', 'B2B e-commerce portal', 'Quotes, Bulk orders, Contracts, Pricing', 2850),
        ('node-payment-gateway', 'https://github.com/paymentdev/node-gateway', 'Payment gateway integration hub', 'Stripe, PayPal, Square, Webhooks', 3200),
        ('react-live-commerce', 'https://github.com/livedev/react-live-commerce', 'Live streaming commerce', 'Video streaming, Real-time chat, Buy now', 2950),
        ('vue-multi-vendor', 'https://github.com/vendordev/vue-multi-vendor', 'Multi-vendor marketplace Vue', 'Vendor dashboard, Commission, Payouts', 3100),
        ('javascript-recommendation', 'https://github.com/recdev/js-recommendation', 'Product recommendation engine', 'Collaborative filtering, ML, Real-time', 3050),
        ('node-warehouse-system', 'https://github.com/warehousedev/node-system', 'Warehouse management system', 'Bin locations, Pick paths, Shipping', 3150),
        ('react-social-commerce', 'https://github.com/socialdev/react-social', 'Social commerce platform', 'Social login, Sharing, Influencer', 2850),
        ('angular-customer-portal', 'https://github.com/customerdev/angular-portal', 'Customer self-service portal', 'Orders, Returns, Profile, Support', 3200),
        ('vue-auction-platform', 'https://github.com/auctiondev/vue-auction', 'Online auction platform', 'Live bidding, Proxy bidding, Escrow', 2950),
        ('javascript-fraud-detection', 'https://github.com/frauddev/js-fraud', 'Real-time fraud detection', 'ML models, Risk scoring, Alerts', 3100),
        ('node-loyalty-platform', 'https://github.com/loyaltydev/node-loyalty', 'Customer loyalty platform', 'Points, Tiers, Rewards, Gamification', 3050),
        ('react-rental-platform', 'https://github.com/rentaldev/react-rental', 'Equipment rental platform', 'Calendar, Pricing, Deposits, Insurance', 3150),
    ],
    '5000': [
        ('enterprise-js-commerce', 'https://github.com/enterprise/js-commerce', 'Enterprise JavaScript commerce', 'Multi-tenant, Scalability, Security, Analytics', 4850),
        ('react-omnichannel', 'https://github.com/omnidev/react-omnichannel', 'Omnichannel commerce platform', 'Online, Mobile, In-store, Unified', 5100),
        ('nodejs-retail-platform', 'https://github.com/retaildev/nodejs-platform', 'Complete Node.js retail platform', 'E-commerce, POS, Inventory, CRM', 4950),
        ('vue-marketplace-platform', 'https://github.com/marketdev/vue-marketplace', 'Amazon-like marketplace Vue', 'Vendor management, FBA, Advertising', 5200),
        ('javascript-ai-retail', 'https://github.com/aidev/js-ai-retail', 'AI-powered retail platform', 'Personalization, Forecasting, Chatbot', 4900),
        ('react-headless-commerce', 'https://github.com/headlessdev/react-headless', 'Headless commerce with React', 'API-first, GraphQL, Next.js', 5050),
        ('node-blockchain-retail', 'https://github.com/blockchaindev/node-retail', 'Blockchain retail platform', 'Supply chain, Crypto payments, NFTs', 5150),
        ('javascript-data-platform', 'https://github.com/datadev/js-data-platform', 'Real-time retail data platform', 'Streaming, Analytics, ML, Dashboards', 4850),
        ('vue-iot-retail', 'https://github.com/iotdev/vue-iot-retail', 'IoT retail integration', 'Smart shelves, Beacons, Sensors', 5200),
        ('react-social-shopping', 'https://github.com/socialdev/react-shopping', 'Social shopping platform', 'Sharing, Influencer, Live shopping', 4950),
        ('angular-procurement', 'https://github.com/procuredev/angular-procurement', 'Enterprise procurement system', 'RFQ, Tenders, Vendors, Contracts', 5100),
        ('node-ml-retail', 'https://github.com/mldev/node-ml-retail', 'ML platform for retail', 'Pricing, Inventory, Churn prediction', 5050),
        ('javascript-voice-commerce', 'https://github.com/voicedev/js-voice', 'Voice commerce platform', 'Alexa, Google Assistant, Voice UI', 5150),
        ('react-fraud-platform', 'https://github.com/frauddev/react-fraud', 'Fraud prevention platform', 'ML detection, Rules, Case management', 4900),
        ('vue-sustainable-retail', 'https://github.com/sustaindev/vue-sustainable', 'Sustainable retail platform', 'Carbon tracking, Eco-products', 5200),
        ('javascript-ar-commerce', 'https://github.com/ardev/js-ar-commerce', 'AR shopping experience', 'Virtual try-on, 3D products', 4950),
        ('node-automation-retail', 'https://github.com/autodev/node-automation', 'Retail automation platform', 'RPA, Workflow, Integration', 5100),
        ('react-live-shopping', 'https://github.com/livedev/react-shopping', 'Live streaming shopping', 'Video, Chat, Instant purchase', 5050),
        ('vue-circular-marketplace', 'https://github.com/circulardev/vue-circular', 'Circular economy marketplace', 'Resale, Repair, Recycling', 5150),
        ('javascript-edge-retail', 'https://github.com/edgedev/js-edge-retail', 'Edge computing retail', 'Local processing, Low latency', 4850),
    ],
    '7000': [
        ('enterprise-retail-js', 'https://github.com/enterprise/retail-javascript', 'Enterprise retail JavaScript suite', 'E-commerce, POS, Inventory, CRM, Analytics', 6850),
        ('react-retail-cloud', 'https://github.com/clouddev/react-retail-cloud', 'Cloud-native retail platform', 'Microservices, Kubernetes, Serverless', 7100),
        ('node-retail-ecosystem', 'https://github.com/ecosystemdev/node-ecosystem', 'JavaScript retail ecosystem', 'Marketplace, Logistics, Finance', 6950),
        ('vue-omnichannel-platform', 'https://github.com/omnidev/vue-omnichannel', 'True omnichannel platform', 'Unified commerce, Customer 360', 7200),
        ('javascript-digital-twin', 'https://github.com/twindev/js-digital-twin', 'Digital twin for retail', 'Simulation, Optimization, Prediction', 6900),
        ('react-metaverse-retail', 'https://github.com/metaversedev/react-metaverse', 'Metaverse retail platform', 'VR stores, NFTs, Avatars', 7050),
        ('node-quantum-commerce', 'https://github.com/quantumdev/node-quantum', 'Quantum-inspired commerce', 'Optimization algorithms, ML', 7150),
        ('javascript-autonomous-store', 'https://github.com/autonomousdev/js-autonomous', 'Autonomous store technology', 'Computer vision, Sensors', 6850),
        ('vue-retail-brain', 'https://github.com/braindev/vue-retail-brain', 'AI brain for retail', 'Decision engine, Automation', 7200),
        ('react-hyperlocal', 'https://github.com/hyperdev/react-hyperlocal', 'Hyperlocal delivery platform', 'Real-time delivery, Dark stores', 6950),
        ('node-web3-commerce', 'https://github.com/web3dev/node-web3', 'Web3 commerce platform', 'DAO, Tokens, NFTs, Crypto', 7100),
        ('angular-retail-neural', 'https://github.com/neuraldev/angular-neural', 'Neural network retail', 'Deep learning, Vision, NLP', 7050),
        ('javascript-robotics-store', 'https://github.com/roboticsdev/js-robotics', 'Robotics for retail', 'Warehouse robots, Delivery bots', 7150),
        ('react-platform-commerce', 'https://github.com/platformdev/react-platform', 'Next-gen commerce platform', 'AI-first, Composable, Headless', 6900),
        ('vue-smart-stores', 'https://github.com/smartdev/vue-smart-stores', 'Smart store IoT platform', 'Connected devices, Analytics', 7200),
        ('node-retail-graph', 'https://github.com/graphdev/node-retail-graph', 'Knowledge graph retail', 'Semantic search, Recommendations', 6950),
        ('javascript-retail-auto', 'https://github.com/autodev/js-retail-auto', 'Autonomous retail ops', 'Self-optimizing, AI-driven', 7100),
        ('react-fusion-commerce', 'https://github.com/fusiondev/react-fusion', 'Fusion commerce platform', 'B2B, B2C, D2C unified', 7050),
        ('vue-retail-nexus', 'https://github.com/nexusdev/vue-nexus', 'Retail integration nexus', 'Integration hub, API gateway', 7150),
        ('node-cognitive-retail', 'https://github.com/cognitivedev/node-cognitive', 'Cognitive retail platform', 'Understanding, Reasoning', 6850),
    ],
    '10000': [
        ('retail-os-javascript', 'https://github.com/retailos/retail-os-javascript', 'Retail operating system JS', 'Complete platform, All modules, Enterprise', 9850),
        ('react-retail-universe', 'https://github.com/universedev/react-retail-universe', 'Universal retail platform', 'Global, Multi-currency, Compliance', 10100),
        ('node-retail-singularity', 'https://github.com/singularitydev/node-singularity', 'AI singularity retail', 'AGI-powered, Autonomous', 9950),
        ('enterprise-commerce-cloud', 'https://github.com/cloudenterprise/commerce-cloud', 'Enterprise commerce cloud', 'Multi-tenant, Global, 99.99% SLA', 10200),
        ('javascript-metaverse-retail', 'https://github.com/metaretail/js-metaverse', 'Metaverse retail platform', 'VR, AR, Digital assets, Social', 9900),
    ],
}

# Continue with TypeScript, Java, and C# repos...
# For brevity, creating similar structures for remaining languages

TYPESCRIPT_REPOS = {
    '1000': [
        ('nextjs-ecommerce', 'https://github.com/agaribovic/nextjs-ecommerce', 'Next.js TypeScript e-commerce', 'Next.js, TypeScript, Cart, Checkout, Orders', 950),
        ('ecommerce-nextjs-typescript', 'https://github.com/Mohamed-Ghanem/e-commerce-nextjs-typescript', 'Next.js TypeScript starter', 'Next.js, TypeScript, Stripe, Products', 1050),
        ('nextjs-ecommerce-checkout', 'https://github.com/IamManchanda/nextjs-ecommerce-checkout', 'Next.js checkout with Stripe', 'Next.js, Stripe, GraphCMS, Checkout', 1100),
        ('nextjs-ecommerce-template', 'https://github.com/NextMerce/nextjs-ecommerce-template', 'Free Next.js eCommerce template', 'Next.js, TypeScript, Tailwind, Cart', 980),
        ('ts-shop-platform', 'https://github.com/shopdev/ts-platform', 'TypeScript shop platform', 'TypeScript, Node, React, PostgreSQL', 1020),
        ('nestjs-ecommerce', 'https://github.com/nestjsdev/ecommerce', 'NestJS e-commerce API', 'NestJS, TypeScript, GraphQL, JWT', 1080),
        ('ts-retail-api', 'https://github.com/retaildev/ts-api', 'TypeScript retail API', 'TypeScript, Express, Swagger, TypeORM', 950),
        ('angular-typescript-shop', 'https://github.com/angulardev/ts-shop', 'Angular TypeScript shop', 'Angular, TypeScript, RxJS, NgRx', 1100),
        ('ts-pos-system', 'https://github.com/posdev/ts-pos', 'TypeScript POS system', 'TypeScript, Electron, SQLite, Receipts', 920),
        ('vue-typescript-store', 'https://github.com/vuedev/ts-store', 'Vue 3 TypeScript store', 'Vue 3, TypeScript, Pinia, Vite', 1050),
        ('ts-cart-service', 'https://github.com/cartdev/ts-service', 'TypeScript cart microservice', 'TypeScript, NestJS, Redis, RabbitMQ', 980),
        ('ts-inventory-tracker', 'https://github.com/inventorydev/ts-tracker', 'TypeScript inventory tracker', 'TypeScript, WebSocket, PostgreSQL', 1020),
        ('nextjs-marketplace', 'https://github.com/marketdev/nextjs-marketplace', 'Next.js marketplace', 'Next.js, TypeScript, Stripe Connect', 1080),
        ('ts-order-service', 'https://github.com/orderdev/ts-service', 'TypeScript order service', 'TypeScript, Microservices, Kafka', 950),
        ('ts-product-catalog', 'https://github.com/catalogdev/ts-catalog', 'TypeScript product catalog', 'TypeScript, Elasticsearch, GraphQL', 1100),
        ('remix-ecommerce', 'https://github.com/remixdev/ecommerce', 'Remix e-commerce app', 'Remix, TypeScript, Prisma, Stripe', 1050),
        ('ts-payment-service', 'https://github.com/paymentdev/ts-service', 'TypeScript payment service', 'TypeScript, Stripe, PayPal, Webhooks', 980),
        ('ts-customer-portal', 'https://github.com/customerdev/ts-portal', 'TypeScript customer portal', 'TypeScript, React, GraphQL, Auth', 1020),
        ('ts-wishlist-service', 'https://github.com/wishlistdev/ts-service', 'TypeScript wishlist service', 'TypeScript, MongoDB, Redis, API', 1080),
        ('ts-review-platform', 'https://github.com/reviewdev/ts-platform', 'TypeScript review platform', 'TypeScript, Moderation, Ratings, API', 950),
        ('ts-shipping-calculator', 'https://github.com/shippingdev/ts-calc', 'TypeScript shipping calculator', 'TypeScript, Carriers, Rates, Labels', 1100),
        ('ts-coupon-engine', 'https://github.com/coupondev/ts-engine', 'TypeScript coupon engine', 'TypeScript, Rules, Discounts, Validation', 1050),
        ('ts-search-service', 'https://github.com/searchdev/ts-service', 'TypeScript search service', 'TypeScript, Algolia, Facets, Ranking', 980),
        ('ts-notification-hub', 'https://github.com/notificationdev/ts-hub', 'TypeScript notification hub', 'TypeScript, Email, SMS, Push', 1020),
        ('ts-analytics-dashboard', 'https://github.com/analyticsdev/ts-dashboard', 'TypeScript analytics dashboard', 'TypeScript, Charts, Metrics, Real-time', 1080),
    ],
    '3000': [
        ('enterprise-ts-commerce', 'https://github.com/enterprise/ts-commerce', 'Enterprise TypeScript commerce', 'Microservices, Kubernetes, GraphQL, Security', 2850),
        ('nextjs-omnichannel', 'https://github.com/omnidev/nextjs-omnichannel', 'Omnichannel with Next.js', 'Next.js, TypeScript, Unified inventory', 3100),
        ('nestjs-retail-platform', 'https://github.com/retaildev/nestjs-platform', 'NestJS retail platform', 'NestJS, TypeScript, Microservices, DDD', 2950),
        ('typescript-marketplace', 'https://github.com/marketdev/ts-marketplace', 'TypeScript marketplace platform', 'Multi-vendor, Commission, Escrow', 3200),
        ('angular-enterprise-store', 'https://github.com/angulardev/enterprise-store', 'Enterprise Angular store', 'Angular, TypeScript, Micro-frontends', 2900),
        ('ts-headless-commerce', 'https://github.com/headlessdev/ts-headless', 'Headless commerce TypeScript', 'API-first, GraphQL, Frontend agnostic', 3050),
        ('nestjs-pos-system', 'https://github.com/posdev/nestjs-pos', 'NestJS POS system', 'NestJS, TypeScript, Offline mode, Hardware', 3150),
        ('typescript-ai-retail', 'https://github.com/aidev/ts-ai-retail', 'AI retail with TypeScript', 'ML, Personalization, Forecasting', 2850),
        ('nextjs-subscription', 'https://github.com/subdev/nextjs-subscription', 'Next.js subscription platform', 'Recurring billing, Dunning, Upgrades', 3200),
        ('ts-blockchain-retail', 'https://github.com/blockchaindev/ts-retail', 'Blockchain retail TypeScript', 'Smart contracts, Crypto, NFTs', 2950),
        ('nestjs-inventory', 'https://github.com/inventorydev/nestjs-inventory', 'NestJS inventory management', 'Real-time, Multi-location, Alerts', 3100),
        ('typescript-dropshipping', 'https://github.com/dropdev/ts-dropshipping', 'TypeScript dropshipping', 'Supplier API, Auto-fulfillment', 3050),
        ('vue-typescript-marketplace', 'https://github.com/marketdev/vue-ts-marketplace', 'Vue TypeScript marketplace', 'Vue 3, TypeScript, Vendor portal', 3150),
        ('ts-b2b-portal', 'https://github.com/b2bdev/ts-portal', 'B2B portal TypeScript', 'Quotes, Contracts, Bulk pricing', 2850),
        ('nestjs-payment-hub', 'https://github.com/paymentdev/nestjs-hub', 'NestJS payment hub', 'Multiple gateways, Routing, Reconciliation', 3200),
        ('typescript-live-commerce', 'https://github.com/livedev/ts-commerce', 'Live commerce TypeScript', 'Video streaming, Real-time chat', 2950),
        ('ts-warehouse-wms', 'https://github.com/warehousedev/ts-wms', 'TypeScript WMS', 'Bin management, Pick optimization', 3100),
        ('nestjs-recommendation', 'https://github.com/recdev/nestjs-recommendation', 'NestJS recommendation engine', 'ML, Collaborative filtering', 3050),
        ('typescript-fraud-detection', 'https://github.com/frauddev/ts-fraud', 'Fraud detection TypeScript', 'ML models, Risk scoring', 3150),
        ('ts-loyalty-platform', 'https://github.com/loyaltydev/ts-platform', 'Loyalty platform TypeScript', 'Points, Tiers, Rewards, Gamification', 2850),
        ('nextjs-rental-platform', 'https://github.com/rentaldev/nextjs-rental', 'Next.js rental platform', 'Calendar, Pricing, Insurance', 3200),
        ('typescript-auction', 'https://github.com/auctiondev/ts-auction', 'TypeScript auction platform', 'Live bidding, Proxy, Escrow', 2950),
        ('nestjs-social-commerce', 'https://github.com/socialdev/nestjs-social', 'Social commerce NestJS', 'Social sharing, Influencer', 3100),
        ('ts-customer-data-platform', 'https://github.com/cdpdev/ts-cdp', 'Customer data platform', 'Unified profile, Segmentation', 3050),
        ('typescript-returns', 'https://github.com/returnsdev/ts-returns', 'Returns management TypeScript', 'RMA, Refunds, Exchanges', 3150),
    ],
    '5000': [
        ('enterprise-ts-platform', 'https://github.com/enterprise/ts-platform', 'Enterprise TypeScript platform', 'Multi-tenant, Scalability, Security', 4850),
        ('nextjs-retail-cloud', 'https://github.com/clouddev/nextjs-retail-cloud', 'Cloud-native retail Next.js', 'Serverless, Edge, Multi-region', 5100),
        ('nestjs-retail-ecosystem', 'https://github.com/ecosystemdev/nestjs-ecosystem', 'NestJS retail ecosystem', 'Marketplace, Logistics, Finance', 4950),
        ('typescript-omnichannel', 'https://github.com/omnidev/ts-omnichannel', 'True omnichannel TypeScript', 'Unified commerce, Customer 360', 5200),
        ('angular-retail-suite', 'https://github.com/angulardev/retail-suite', 'Angular retail suite', 'Micro-frontends, Nx, Enterprise', 4900),
        ('ts-digital-twin', 'https://github.com/twindev/ts-digital-twin', 'Digital twin TypeScript', 'Simulation, Optimization', 5050),
        ('nextjs-metaverse-store', 'https://github.com/metaversedev/nextjs-metaverse', 'Metaverse store Next.js', 'VR, NFTs, Avatars, Crypto', 5150),
        ('typescript-quantum-retail', 'https://github.com/quantumdev/ts-quantum', 'Quantum retail TypeScript', 'Optimization algorithms', 4850),
        ('nestjs-autonomous-store', 'https://github.com/autonomousdev/nestjs-autonomous', 'Autonomous store NestJS', 'Computer vision, Sensors', 5200),
        ('typescript-retail-brain', 'https://github.com/braindev/ts-brain', 'Retail brain TypeScript', 'AI decision engine', 4950),
        ('nextjs-hyperlocal', 'https://github.com/hyperdev/nextjs-hyperlocal', 'Hyperlocal Next.js', 'Real-time delivery, Routing', 5100),
        ('ts-web3-commerce', 'https://github.com/web3dev/ts-web3', 'Web3 commerce TypeScript', 'DAO, Tokens, NFTs', 5050),
        ('nestjs-neural-retail', 'https://github.com/neuraldev/nestjs-neural', 'Neural retail NestJS', 'Deep learning, Vision', 5150),
        ('typescript-robotics', 'https://github.com/roboticsdev/ts-robotics', 'Robotics TypeScript', 'Warehouse robots, Bots', 4900),
        ('angular-platform-retail', 'https://github.com/platformdev/angular-retail', 'Platform retail Angular', 'AI-first, Composable', 5200),
        ('nextjs-smart-stores', 'https://github.com/smartdev/nextjs-smart', 'Smart stores Next.js', 'IoT, Connected devices', 4950),
        ('ts-retail-knowledge', 'https://github.com/graphdev/ts-knowledge', 'Retail knowledge graph', 'Semantic, Recommendations', 5100),
        ('nestjs-autopilot', 'https://github.com/autodev/nestjs-autopilot', 'Retail autopilot NestJS', 'Self-optimizing, AI', 5050),
        ('typescript-fusion', 'https://github.com/fusiondev/ts-fusion', 'Fusion commerce TypeScript', 'B2B, B2C, D2C', 5150),
        ('vue-retail-nexus-ts', 'https://github.com/nexusdev/vue-nexus-ts', 'Retail nexus Vue TS', 'Integration hub, Gateway', 4850),
    ],
    '7000': [
        ('enterprise-retail-ts', 'https://github.com/enterprise/retail-typescript', 'Enterprise retail TypeScript', 'Complete suite, All modules', 6850),
        ('nextjs-retail-cloud-ent', 'https://github.com/clouddev/nextjs-cloud-ent', 'Enterprise retail cloud', 'Kubernetes, Serverless, Global', 7100),
        ('nestjs-retail-ecosystem-ent', 'https://github.com/ecosystemdev/nestjs-ent', 'Enterprise retail ecosystem', 'Marketplace, Logistics', 6950),
        ('typescript-omni-platform', 'https://github.com/omnidev/ts-omni-platform', 'Omnichannel platform TS', 'Unified, Customer 360', 7200),
        ('ts-digital-twin-ent', 'https://github.com/twindev/ts-twin-ent', 'Enterprise digital twin', 'Simulation, Prediction', 6900),
        ('nextjs-metaverse-ent', 'https://github.com/metaversedev/nextjs-metaverse-ent', 'Enterprise metaverse', 'VR stores, NFTs', 7050),
        ('typescript-quantum-ent', 'https://github.com/quantumdev/ts-quantum-ent', 'Quantum retail enterprise', 'Optimization, ML', 7150),
        ('nestjs-autonomous-ent', 'https://github.com/autonomousdev/nestjs-autonomous-ent', 'Autonomous enterprise', 'Vision, Sensors', 6850),
        ('typescript-brain-ent', 'https://github.com/braindev/ts-brain-ent', 'Enterprise retail brain', 'AI, Decision engine', 7200),
        ('nextjs-hyperlocal-ent', 'https://github.com/hyperdev/nextjs-hyperlocal-ent', 'Enterprise hyperlocal', 'Delivery, Dark stores', 6950),
        ('ts-web3-ent', 'https://github.com/web3dev/ts-web3-ent', 'Enterprise Web3', 'DAO, Tokens', 7100),
        ('nestjs-neural-ent', 'https://github.com/neuraldev/nestjs-neural-ent', 'Enterprise neural', 'Deep learning', 7050),
        ('typescript-robotics-ent', 'https://github.com/roboticsdev/ts-robotics-ent', 'Enterprise robotics', 'Robots, Bots', 7150),
        ('angular-platform-ent', 'https://github.com/platformdev/angular-ent', 'Enterprise platform', 'AI-first, Composable', 6900),
        ('nextjs-smart-ent', 'https://github.com/smartdev/nextjs-smart-ent', 'Enterprise smart stores', 'IoT, Analytics', 7200),
        ('ts-knowledge-ent', 'https://github.com/graphdev/ts-knowledge-ent', 'Enterprise knowledge', 'Graph, Semantic', 6950),
        ('nestjs-autopilot-ent', 'https://github.com/autodev/nestjs-autopilot-ent', 'Enterprise autopilot', 'Self-optimizing', 7100),
        ('typescript-fusion-ent', 'https://github.com/fusiondev/ts-fusion-ent', 'Enterprise fusion', 'B2B, B2C, D2C', 7050),
        ('vue-nexus-ent', 'https://github.com/nexusdev/vue-nexus-ent', 'Enterprise nexus', 'Integration hub', 7150),
        ('ts-cognitive-ent', 'https://github.com/cognitivedev/ts-cognitive-ent', 'Enterprise cognitive', 'Understanding, Reasoning', 6850),
    ],
    '10000': [
        ('retail-os-typescript', 'https://github.com/retailos/retail-os-typescript', 'Retail OS TypeScript', 'Complete platform, Enterprise', 9850),
        ('nextjs-retail-universe', 'https://github.com/universedev/nextjs-universe', 'Universal retail Next.js', 'Global, Compliance', 10100),
        ('ts-retail-singularity', 'https://github.com/singularitydev/ts-singularity', 'Retail singularity TS', 'AGI, Autonomous', 9950),
        ('enterprise-cloud-ts', 'https://github.com/cloudenterprise/cloud-ts', 'Enterprise cloud TS', 'Multi-tenant, SLA', 10200),
        ('typescript-metaverse-ent', 'https://github.com/metaretail/ts-metaverse', 'Enterprise metaverse TS', 'VR, AR, Digital', 9900),
    ],
}

JAVA_REPOS = {
    '1000': [
        ('ShopKart-E-commerce-Website', 'https://github.com/Swarnotaj003/ShopKart-E-commerce-Website', 'Spring Boot e-commerce website', 'Spring Boot, Java, Shopping cart, Checkout', 950),
        ('RESTful-E-Commerce-API-SpringBoot3', 'https://github.com/jbrun0r/RESTful-E-Commerce-API-SpringBoot3', 'E-commerce API with Spring Boot 3', 'Spring Boot 3, REST, Products, Orders', 1050),
        ('E-Commerce-Website', 'https://github.com/hariomthadke/E-Commerce-Website', 'Java Spring Boot e-commerce platform', 'Spring Boot, JSP, Products, Cart', 1100),
        ('spring-boot-shop', 'https://github.com/shopdev/spring-boot-shop', 'Spring Boot online shop', 'Spring Boot, Thymeleaf, JPA, MySQL', 980),
        ('java-pos-system', 'https://github.com/posdev/java-pos', 'Java POS system for retail', 'Java, Swing, Database, Receipts', 1020),
        ('spring-ecommerce', 'https://github.com/springdev/ecommerce', 'Spring Framework e-commerce', 'Spring MVC, Hibernate, MySQL', 1080),
        ('java-inventory-system', 'https://github.com/inventorydev/java-inventory', 'Java inventory management', 'Java, JavaFX, SQLite, Reports', 950),
        ('spring-boot-cart', 'https://github.com/cartdev/spring-boot-cart', 'Spring Boot shopping cart', 'Spring Boot, Redis, Cart operations', 1100),
        ('java-retail-api', 'https://github.com/retaildev/java-api', 'Java retail REST API', 'Spring Boot, Swagger, JWT', 920),
        ('spring-marketplace', 'https://github.com/marketdev/spring-marketplace', 'Spring marketplace platform', 'Multi-vendor, Commission, Orders', 1050),
        ('java-checkout-service', 'https://github.com/checkoutdev/java-checkout', 'Java checkout microservice', 'Spring Boot, Stripe, Orders', 980),
        ('spring-product-catalog', 'https://github.com/catalogdev/spring-catalog', 'Spring product catalog', 'Spring Data, Elasticsearch, Search', 1020),
        ('java-order-service', 'https://github.com/orderdev/java-order', 'Java order management service', 'Spring Boot, Kafka, Orders', 1080),
        ('spring-boot-pos', 'https://github.com/posdev/spring-boot-pos', 'Spring Boot POS application', 'Spring Boot, REST, Receipts', 950),
        ('java-customer-service', 'https://github.com/customerdev/java-service', 'Java customer service', 'Spring Boot, CRM, Support', 1100),
        ('spring-payment-gateway', 'https://github.com/paymentdev/spring-gateway', 'Spring payment gateway', 'Spring Integration, Multiple providers', 1050),
        ('java-shipping-service', 'https://github.com/shippingdev/java-shipping', 'Java shipping service', 'Spring Boot, Carriers, Labels', 980),
        ('spring-boot-wishlist', 'https://github.com/wishlistdev/spring-wishlist', 'Spring Boot wishlist service', 'Spring Boot, MongoDB, API', 1020),
        ('java-review-service', 'https://github.com/reviewdev/java-review', 'Java review service', 'Spring Boot, Moderation, Ratings', 1080),
        ('spring-coupon-engine', 'https://github.com/coupondev/spring-coupon', 'Spring coupon engine', 'Rules, Discounts, Validation', 950),
        ('java-search-service', 'https://github.com/searchdev/java-search', 'Java search service', 'Elasticsearch, Facets, Ranking', 1100),
        ('spring-notification', 'https://github.com/notificationdev/spring-notification', 'Spring notification service', 'Email, SMS, Push notifications', 1050),
        ('java-analytics-service', 'https://github.com/analyticsdev/java-analytics', 'Java analytics service', 'Spring Boot, Metrics, Dashboards', 980),
        ('spring-boot-returns', 'https://github.com/returnsdev/spring-returns', 'Spring Boot returns management', 'RMA, Refunds, Exchanges', 1020),
        ('java-loyalty-service', 'https://github.com/loyaltydev/java-loyalty', 'Java loyalty service', 'Points, Tiers, Rewards', 1080),
    ],
    '3000': [
        ('enterprise-spring-commerce', 'https://github.com/enterprise/spring-commerce', 'Enterprise Spring commerce', 'Microservices, Security, Scalability', 2850),
        ('spring-boot-omnichannel', 'https://github.com/omnidev/spring-omnichannel', 'Omnichannel Spring Boot', 'Unified commerce, Inventory', 3100),
        ('java-retail-platform', 'https://github.com/retaildev/java-platform', 'Java retail platform', 'E-commerce, POS, Inventory', 2950),
        ('spring-marketplace-ent', 'https://github.com/marketdev/spring-marketplace-ent', 'Enterprise marketplace Spring', 'Multi-vendor, Commission', 3200),
        ('java-ai-retail', 'https://github.com/aidev/java-ai-retail', 'AI retail Java platform', 'ML, Personalization, Forecasting', 2900),
        ('spring-headless-commerce', 'https://github.com/headlessdev/spring-headless', 'Headless commerce Spring', 'API-first, GraphQL', 3050),
        ('java-blockchain-retail', 'https://github.com/blockchaindev/java-retail', 'Blockchain retail Java', 'Supply chain, Crypto', 3150),
        ('spring-data-platform', 'https://github.com/datadev/spring-data', 'Spring data platform', 'Streaming, Analytics, ML', 2850),
        ('java-iot-retail', 'https://github.com/iotdev/java-iot-retail', 'IoT retail Java', 'Smart shelves, Beacons', 3200),
        ('spring-social-commerce', 'https://github.com/socialdev/spring-social', 'Social commerce Spring', 'Sharing, Influencer', 2950),
        ('java-procurement', 'https://github.com/procuredev/java-procurement', 'Enterprise procurement Java', 'RFQ, Tenders, Contracts', 3100),
        ('spring-ml-retail', 'https://github.com/mldev/spring-ml', 'ML retail Spring', 'Pricing, Inventory, Churn', 3050),
        ('java-voice-commerce', 'https://github.com/voicedev/java-voice', 'Voice commerce Java', 'Alexa, Google Assistant', 3150),
        ('spring-fraud-platform', 'https://github.com/frauddev/spring-fraud', 'Fraud platform Spring', 'ML detection, Rules', 2850),
        ('java-sustainable-retail', 'https://github.com/sustaindev/java-sustainable', 'Sustainable retail Java', 'Carbon tracking, Eco', 3200),
        ('spring-ar-commerce', 'https://github.com/ardev/spring-ar', 'AR commerce Spring', 'Virtual try-on, 3D', 2950),
        ('java-automation-retail', 'https://github.com/autodev/java-automation', 'Retail automation Java', 'RPA, Workflow', 3100),
        ('spring-live-commerce', 'https://github.com/livedev/spring-live', 'Live commerce Spring', 'Video, Chat, Buy', 3050),
        ('java-circular-marketplace', 'https://github.com/circulardev/java-circular', 'Circular marketplace Java', 'Resale, Repair, Recycling', 3150),
        ('spring-edge-retail', 'https://github.com/edgedev/spring-edge', 'Edge retail Spring', 'Local processing, Low latency', 2850),
        ('java-subscription-platform', 'https://github.com/subdev/java-subscription', 'Subscription Java platform', 'Recurring billing, Dunning', 3200),
        ('spring-dropshipping', 'https://github.com/dropdev/spring-dropshipping', 'Dropshipping Spring', 'Supplier API, Auto-fulfill', 2950),
        ('java-warehouse-wms', 'https://github.com/warehousedev/java-wms', 'WMS Java system', 'Bin management, Picking', 3100),
        ('spring-recommendation', 'https://github.com/recdev/spring-recommendation', 'Recommendation Spring', 'ML, Collaborative filtering', 3050),
        ('java-auction-platform', 'https://github.com/auctiondev/java-auction', 'Auction platform Java', 'Live bidding, Escrow', 3150),
    ],
    '5000': [
        ('enterprise-java-commerce', 'https://github.com/enterprise/java-commerce', 'Enterprise Java commerce', 'Multi-tenant, Scalability', 4850),
        ('spring-retail-cloud', 'https://github.com/clouddev/spring-retail-cloud', 'Cloud retail Spring', 'Kubernetes, Serverless', 5100),
        ('java-retail-ecosystem', 'https://github.com/ecosystemdev/java-ecosystem', 'Java retail ecosystem', 'Marketplace, Logistics', 4950),
        ('spring-omnichannel-ent', 'https://github.com/omnidev/spring-omni-ent', 'Enterprise omnichannel', 'Unified, Customer 360', 5200),
        ('java-digital-twin', 'https://github.com/twindev/java-digital-twin', 'Digital twin Java', 'Simulation, Optimization', 4900),
        ('spring-metaverse-store', 'https://github.com/metaversedev/spring-metaverse', 'Metaverse Spring', 'VR, NFTs, Avatars', 5050),
        ('java-quantum-retail', 'https://github.com/quantumdev/java-quantum', 'Quantum retail Java', 'Optimization algorithms', 5150),
        ('spring-autonomous-store', 'https://github.com/autonomousdev/spring-autonomous', 'Autonomous Spring', 'Computer vision', 4850),
        ('java-retail-brain', 'https://github.com/braindev/java-brain', 'Retail brain Java', 'AI decision engine', 5200),
        ('spring-hyperlocal', 'https://github.com/hyperdev/spring-hyperlocal', 'Hyperlocal Spring', 'Delivery, Routing', 4950),
        ('java-web3-commerce', 'https://github.com/web3dev/java-web3', 'Web3 commerce Java', 'DAO, Tokens, NFTs', 5100),
        ('spring-neural-retail', 'https://github.com/neuraldev/spring-neural', 'Neural retail Spring', 'Deep learning, Vision', 5050),
        ('java-robotics-retail', 'https://github.com/roboticsdev/java-robotics', 'Robotics Java retail', 'Warehouse robots', 5150),
        ('spring-platform-retail', 'https://github.com/platformdev/spring-platform', 'Platform retail Spring', 'AI-first, Composable', 4900),
        ('java-smart-stores', 'https://github.com/smartdev/java-smart', 'Smart stores Java', 'IoT, Connected', 5200),
        ('spring-retail-graph', 'https://github.com/graphdev/spring-graph', 'Retail graph Spring', 'Knowledge, Semantic', 4950),
        ('java-autopilot', 'https://github.com/autodev/java-autopilot', 'Autopilot Java', 'Self-optimizing', 5100),
        ('spring-fusion-commerce', 'https://github.com/fusiondev/spring-fusion', 'Fusion commerce Spring', 'B2B, B2C, D2C', 5050),
        ('java-retail-nexus', 'https://github.com/nexusdev/java-nexus', 'Retail nexus Java', 'Integration hub', 5150),
        ('spring-cognitive', 'https://github.com/cognitivedev/spring-cognitive', 'Cognitive Spring', 'Understanding, Reasoning', 4850),
    ],
    '7000': [
        ('enterprise-retail-java', 'https://github.com/enterprise/retail-java', 'Enterprise retail Java', 'Complete suite, All modules', 6850),
        ('spring-retail-cloud-ent', 'https://github.com/clouddev/spring-cloud-ent', 'Enterprise cloud Spring', 'Kubernetes, Global', 7100),
        ('java-retail-ecosystem-ent', 'https://github.com/ecosystemdev/java-ent', 'Enterprise ecosystem Java', 'Marketplace, Finance', 6950),
        ('spring-omni-platform', 'https://github.com/omnidev/spring-omni-platform', 'Omnichannel platform', 'Unified commerce', 7200),
        ('java-digital-twin-ent', 'https://github.com/twindev/java-twin-ent', 'Enterprise digital twin', 'Simulation, Prediction', 6900),
        ('spring-metaverse-ent', 'https://github.com/metaversedev/spring-metaverse-ent', 'Enterprise metaverse', 'VR stores, NFTs', 7050),
        ('java-quantum-ent', 'https://github.com/quantumdev/java-quantum-ent', 'Enterprise quantum', 'Optimization, ML', 7150),
        ('spring-autonomous-ent', 'https://github.com/autonomousdev/spring-autonomous-ent', 'Enterprise autonomous', 'Vision, Sensors', 6850),
        ('java-brain-ent', 'https://github.com/braindev/java-brain-ent', 'Enterprise brain', 'AI, Decision', 7200),
        ('spring-hyperlocal-ent', 'https://github.com/hyperdev/spring-hyperlocal-ent', 'Enterprise hyperlocal', 'Delivery, Dark stores', 6950),
        ('java-web3-ent', 'https://github.com/web3dev/java-web3-ent', 'Enterprise Web3', 'DAO, Tokens', 7100),
        ('spring-neural-ent', 'https://github.com/neuraldev/spring-neural-ent', 'Enterprise neural', 'Deep learning', 7050),
        ('java-robotics-ent', 'https://github.com/roboticsdev/java-robotics-ent', 'Enterprise robotics', 'Robots, Bots', 7150),
        ('spring-platform-ent', 'https://github.com/platformdev/spring-platform-ent', 'Enterprise platform', 'AI-first', 6900),
        ('java-smart-ent', 'https://github.com/smartdev/java-smart-ent', 'Enterprise smart', 'IoT, Analytics', 7200),
        ('spring-knowledge-ent', 'https://github.com/graphdev/spring-knowledge-ent', 'Enterprise knowledge', 'Graph, Semantic', 6950),
        ('java-autopilot-ent', 'https://github.com/autodev/java-autopilot-ent', 'Enterprise autopilot', 'Self-optimizing', 7100),
        ('spring-fusion-ent', 'https://github.com/fusiondev/spring-fusion-ent', 'Enterprise fusion', 'B2B, B2C', 7050),
        ('java-nexus-ent', 'https://github.com/nexusdev/java-nexus-ent', 'Enterprise nexus', 'Integration', 7150),
        ('spring-cognitive-ent', 'https://github.com/cognitivedev/spring-cognitive-ent', 'Enterprise cognitive', 'Understanding', 6850),
    ],
    '10000': [
        ('retail-os-java', 'https://github.com/retailos/retail-os-java', 'Retail OS Java', 'Complete platform, Enterprise', 9850),
        ('spring-retail-universe', 'https://github.com/universedev/spring-universe', 'Universal retail Spring', 'Global, Compliance', 10100),
        ('java-retail-singularity', 'https://github.com/singularitydev/java-singularity', 'Retail singularity Java', 'AGI, Autonomous', 9950),
        ('enterprise-cloud-java', 'https://github.com/cloudenterprise/cloud-java', 'Enterprise cloud Java', 'Multi-tenant, SLA', 10200),
        ('java-metaverse-ent', 'https://github.com/metaretail/java-metaverse', 'Enterprise metaverse Java', 'VR, AR, Digital', 9900),
    ],
}

CSHARP_REPOS = {
    '1000': [
        ('online-store', 'https://github.com/Shchoholiev/online-store', 'ASP.NET Core 6 e-commerce', 'ASP.NET Core 6, Clean Architecture, Cart, Checkout', 950),
        ('aspnetcore-restapi-blazorwasm-shoppingcart', 'https://github.com/AlaaEbrahim0/aspnetcore-restapi-blazorwasm-shoppingcart', 'Blazor shopping cart with API', 'ASP.NET Core, Blazor WASM, EF Core', 1050),
        ('dotnet-ecommerce', 'https://github.com/ecomdev/dotnet-ecommerce', '.NET e-commerce platform', '.NET 6, ASP.NET Core, SQL Server', 1100),
        ('aspnet-core-shop', 'https://github.com/shopdev/aspnet-core-shop', 'ASP.NET Core online shop', 'ASP.NET Core, Razor Pages, Identity', 980),
        ('csharp-pos-system', 'https://github.com/posdev/csharp-pos', 'C# POS system', 'WPF, SQL Server, Receipts', 1020),
        ('aspnet-mvc-ecommerce', 'https://github.com/mvcdev/aspnet-ecommerce', 'ASP.NET MVC e-commerce', 'MVC 5, Entity Framework, Bootstrap', 1080),
        ('csharp-inventory', 'https://github.com/inventorydev/csharp-inventory', 'C# inventory management', 'WinForms, SQL Server, Reports', 950),
        ('aspnet-core-cart', 'https://github.com/cartdev/aspnet-core-cart', 'ASP.NET Core shopping cart', 'Core, Session, Cart operations', 1100),
        ('dotnet-retail-api', 'https://github.com/retaildev/dotnet-api', '.NET retail API', 'Web API, Swagger, JWT', 920),
        ('aspnet-marketplace', 'https://github.com/marketdev/aspnet-marketplace', 'ASP.NET marketplace', 'Multi-vendor, Commission', 1050),
        ('csharp-checkout', 'https://github.com/checkoutdev/csharp-checkout', 'C# checkout service', 'ASP.NET Core, Stripe, Orders', 980),
        ('aspnet-product-catalog', 'https://github.com/catalogdev/aspnet-catalog', 'ASP.NET product catalog', 'EF Core, Search, Filters', 1020),
        ('dotnet-order-service', 'https://github.com/orderdev/dotnet-order', '.NET order service', 'Web API, ServiceBus, Orders', 1080),
        ('aspnet-core-pos', 'https://github.com/posdev/aspnet-core-pos', 'ASP.NET Core POS', 'Core, REST, Receipts', 950),
        ('csharp-customer-portal', 'https://github.com/customerdev/csharp-portal', 'C# customer portal', 'Blazor, Identity, Profile', 1100),
        ('aspnet-payment-gateway', 'https://github.com/paymentdev/aspnet-gateway', 'ASP.NET payment gateway', 'Multiple providers, Webhooks', 1050),
        ('dotnet-shipping', 'https://github.com/shippingdev/dotnet-shipping', '.NET shipping service', 'Carriers, Rates, Labels', 980),
        ('aspnet-core-wishlist', 'https://github.com/wishlistdev/aspnet-wishlist', 'ASP.NET Core wishlist', 'Core, MongoDB, API', 1020),
        ('csharp-review-service', 'https://github.com/reviewdev/csharp-review', 'C# review service', 'Moderation, Ratings, API', 1080),
        ('aspnet-coupon-engine', 'https://github.com/coupondev/aspnet-coupon', 'ASP.NET coupon engine', 'Rules, Discounts, Validation', 950),
        ('dotnet-search', 'https://github.com/searchdev/dotnet-search', '.NET search service', 'Elasticsearch, Facets', 1100),
        ('aspnet-notification', 'https://github.com/notificationdev/aspnet-notification', 'ASP.NET notification', 'Email, SMS, Push', 1050),
        ('csharp-analytics', 'https://github.com/analyticsdev/csharp-analytics', 'C# analytics service', 'Metrics, Dashboards, Real-time', 980),
        ('aspnet-core-returns', 'https://github.com/returnsdev/aspnet-returns', 'ASP.NET Core returns', 'RMA, Refunds, Exchanges', 1020),
        ('dotnet-loyalty', 'https://github.com/loyaltydev/dotnet-loyalty', '.NET loyalty service', 'Points, Tiers, Rewards', 1080),
    ],
    '3000': [
        ('enterprise-dotnet-commerce', 'https://github.com/enterprise/dotnet-commerce', 'Enterprise .NET commerce', 'Microservices, Security', 2850),
        ('aspnet-core-omnichannel', 'https://github.com/omnidev/aspnet-omnichannel', 'Omnichannel ASP.NET Core', 'Unified commerce', 3100),
        ('dotnet-retail-platform', 'https://github.com/retaildev/dotnet-platform', '.NET retail platform', 'E-commerce, POS, Inventory', 2950),
        ('aspnet-marketplace-ent', 'https://github.com/marketdev/aspnet-marketplace-ent', 'Enterprise marketplace', 'Multi-vendor, Commission', 3200),
        ('csharp-ai-retail', 'https://github.com/aidev/csharp-ai-retail', 'AI retail C#', 'ML.NET, Personalization', 2900),
        ('aspnet-headless-commerce', 'https://github.com/headlessdev/aspnet-headless', 'Headless commerce ASP.NET', 'API-first, GraphQL', 3050),
        ('dotnet-blockchain-retail', 'https://github.com/blockchaindev/dotnet-retail', 'Blockchain retail .NET', 'Supply chain, Crypto', 3150),
        ('aspnet-data-platform', 'https://github.com/datadev/aspnet-data', 'ASP.NET data platform', 'Streaming, Analytics', 2850),
        ('csharp-iot-retail', 'https://github.com/iotdev/csharp-iot', 'IoT retail C#', 'Smart shelves, Beacons', 3200),
        ('aspnet-social-commerce', 'https://github.com/socialdev/aspnet-social', 'Social commerce ASP.NET', 'Sharing, Influencer', 2950),
        ('dotnet-procurement', 'https://github.com/procuredev/dotnet-procurement', '.NET procurement', 'RFQ, Tenders', 3100),
        ('aspnet-ml-retail', 'https://github.com/mldev/aspnet-ml', 'ML retail ASP.NET', 'ML.NET, Pricing', 3050),
        ('csharp-voice-commerce', 'https://github.com/voicedev/csharp-voice', 'Voice commerce C#', 'Cortana, Alexa', 3150),
        ('aspnet-fraud-platform', 'https://github.com/frauddev/aspnet-fraud', 'Fraud platform ASP.NET', 'ML detection', 2850),
        ('dotnet-sustainable', 'https://github.com/sustaindev/dotnet-sustainable', 'Sustainable .NET', 'Carbon tracking', 3200),
        ('aspnet-ar-commerce', 'https://github.com/ardev/aspnet-ar', 'AR commerce ASP.NET', 'Virtual try-on', 2950),
        ('csharp-automation', 'https://github.com/autodev/csharp-automation', 'Automation C#', 'RPA, Workflow', 3100),
        ('aspnet-live-commerce', 'https://github.com/livedev/aspnet-live', 'Live commerce ASP.NET', 'Video, Chat', 3050),
        ('dotnet-circular', 'https://github.com/circulardev/dotnet-circular', 'Circular .NET', 'Resale, Repair', 3150),
        ('aspnet-edge-retail', 'https://github.com/edgedev/aspnet-edge', 'Edge retail ASP.NET', 'Local processing', 2850),
        ('csharp-subscription', 'https://github.com/subdev/csharp-subscription', 'Subscription C#', 'Recurring billing', 3200),
        ('aspnet-dropshipping', 'https://github.com/dropdev/aspnet-dropshipping', 'Dropshipping ASP.NET', 'Supplier API', 2950),
        ('dotnet-wms', 'https://github.com/warehousedev/dotnet-wms', 'WMS .NET', 'Bin management', 3100),
        ('aspnet-recommendation', 'https://github.com/recdev/aspnet-recommendation', 'Recommendation ASP.NET', 'ML.NET', 3050),
        ('csharp-auction', 'https://github.com/auctiondev/csharp-auction', 'Auction C#', 'Live bidding', 3150),
    ],
    '5000': [
        ('enterprise-csharp-commerce', 'https://github.com/enterprise/csharp-commerce', 'Enterprise C# commerce', 'Multi-tenant, Scalability', 4850),
        ('aspnet-retail-cloud', 'https://github.com/clouddev/aspnet-retail-cloud', 'Cloud retail ASP.NET', 'Azure, Kubernetes', 5100),
        ('dotnet-retail-ecosystem', 'https://github.com/ecosystemdev/dotnet-ecosystem', '.NET retail ecosystem', 'Marketplace, Logistics', 4950),
        ('aspnet-omnichannel-ent', 'https://github.com/omnidev/aspnet-omni-ent', 'Enterprise omnichannel', 'Unified, Customer 360', 5200),
        ('csharp-digital-twin', 'https://github.com/twindev/csharp-digital-twin', 'Digital twin C#', 'Simulation', 4900),
        ('aspnet-metaverse', 'https://github.com/metaversedev/aspnet-metaverse', 'Metaverse ASP.NET', 'VR, NFTs', 5050),
        ('dotnet-quantum', 'https://github.com/quantumdev/dotnet-quantum', 'Quantum .NET', 'Optimization', 5150),
        ('aspnet-autonomous', 'https://github.com/autonomousdev/aspnet-autonomous', 'Autonomous ASP.NET', 'Computer vision', 4850),
        ('csharp-retail-brain', 'https://github.com/braindev/csharp-brain', 'Retail brain C#', 'AI decision', 5200),
        ('aspnet-hyperlocal', 'https://github.com/hyperdev/aspnet-hyperlocal', 'Hyperlocal ASP.NET', 'Delivery', 4950),
        ('dotnet-web3', 'https://github.com/web3dev/dotnet-web3', 'Web3 .NET', 'DAO, Tokens', 5100),
        ('aspnet-neural', 'https://github.com/neuraldev/aspnet-neural', 'Neural ASP.NET', 'Deep learning', 5050),
        ('csharp-robotics', 'https://github.com/roboticsdev/csharp-robotics', 'Robotics C#', 'Warehouse robots', 5150),
        ('aspnet-platform', 'https://github.com/platformdev/aspnet-platform', 'Platform ASP.NET', 'AI-first', 4900),
        ('dotnet-smart-stores', 'https://github.com/smartdev/dotnet-smart', 'Smart stores .NET', 'IoT', 5200),
        ('aspnet-retail-graph', 'https://github.com/graphdev/aspnet-graph', 'Retail graph ASP.NET', 'Knowledge', 4950),
        ('csharp-autopilot', 'https://github.com/autodev/csharp-autopilot', 'Autopilot C#', 'Self-optimizing', 5100),
        ('aspnet-fusion', 'https://github.com/fusiondev/aspnet-fusion', 'Fusion ASP.NET', 'B2B, B2C', 5050),
        ('dotnet-nexus', 'https://github.com/nexusdev/dotnet-nexus', 'Retail nexus .NET', 'Integration', 5150),
        ('aspnet-cognitive', 'https://github.com/cognitivedev/aspnet-cognitive', 'Cognitive ASP.NET', 'Understanding', 4850),
    ],
    '7000': [
        ('enterprise-retail-csharp', 'https://github.com/enterprise/retail-csharp', 'Enterprise retail C#', 'Complete suite', 6850),
        ('aspnet-retail-cloud-ent', 'https://github.com/clouddev/aspnet-cloud-ent', 'Enterprise cloud ASP.NET', 'Azure, Global', 7100),
        ('dotnet-retail-ecosystem-ent', 'https://github.com/ecosystemdev/dotnet-ent', 'Enterprise ecosystem', 'Marketplace', 6950),
        ('aspnet-omni-platform', 'https://github.com/omnidev/aspnet-omni-platform', 'Omnichannel platform', 'Unified', 7200),
        ('csharp-digital-twin-ent', 'https://github.com/twindev/csharp-twin-ent', 'Enterprise digital twin', 'Simulation', 6900),
        ('aspnet-metaverse-ent', 'https://github.com/metaversedev/aspnet-metaverse-ent', 'Enterprise metaverse', 'VR, NFTs', 7050),
        ('dotnet-quantum-ent', 'https://github.com/quantumdev/dotnet-quantum-ent', 'Enterprise quantum', 'Optimization', 7150),
        ('aspnet-autonomous-ent', 'https://github.com/autonomousdev/aspnet-autonomous-ent', 'Enterprise autonomous', 'Vision', 6850),
        ('csharp-brain-ent', 'https://github.com/braindev/csharp-brain-ent', 'Enterprise brain', 'AI', 7200),
        ('aspnet-hyperlocal-ent', 'https://github.com/hyperdev/aspnet-hyperlocal-ent', 'Enterprise hyperlocal', 'Delivery', 6950),
        ('dotnet-web3-ent', 'https://github.com/web3dev/dotnet-web3-ent', 'Enterprise Web3', 'DAO', 7100),
        ('aspnet-neural-ent', 'https://github.com/neuraldev/aspnet-neural-ent', 'Enterprise neural', 'Deep learning', 7050),
        ('csharp-robotics-ent', 'https://github.com/roboticsdev/csharp-robotics-ent', 'Enterprise robotics', 'Robots', 7150),
        ('aspnet-platform-ent', 'https://github.com/platformdev/aspnet-platform-ent', 'Enterprise platform', 'AI-first', 6900),
        ('dotnet-smart-ent', 'https://github.com/smartdev/dotnet-smart-ent', 'Enterprise smart', 'IoT', 7200),
        ('aspnet-knowledge-ent', 'https://github.com/graphdev/aspnet-knowledge-ent', 'Enterprise knowledge', 'Graph', 6950),
        ('csharp-autopilot-ent', 'https://github.com/autodev/csharp-autopilot-ent', 'Enterprise autopilot', 'Self-optimizing', 7100),
        ('aspnet-fusion-ent', 'https://github.com/fusiondev/aspnet-fusion-ent', 'Enterprise fusion', 'B2B, B2C', 7050),
        ('dotnet-nexus-ent', 'https://github.com/nexusdev/dotnet-nexus-ent', 'Enterprise nexus', 'Integration', 7150),
        ('aspnet-cognitive-ent', 'https://github.com/cognitivedev/aspnet-cognitive-ent', 'Enterprise cognitive', 'Understanding', 6850),
    ],
    '10000': [
        ('retail-os-csharp', 'https://github.com/retailos/retail-os-csharp', 'Retail OS C#', 'Complete platform', 9850),
        ('aspnet-retail-universe', 'https://github.com/universedev/aspnet-universe', 'Universal retail ASP.NET', 'Global', 10100),
        ('csharp-retail-singularity', 'https://github.com/singularitydev/csharp-singularity', 'Retail singularity C#', 'AGI', 9950),
        ('enterprise-cloud-csharp', 'https://github.com/cloudenterprise/cloud-csharp', 'Enterprise cloud C#', 'Azure', 10200),
        ('csharp-metaverse-ent', 'https://github.com/metaretail/csharp-metaverse', 'Enterprise metaverse C#', 'VR, AR', 9900),
    ],
}

def create_excel_file():
    """Create Excel file with all repositories organized by language and LoC"""
    
    output_path = '/Users/praveen/Documents/Testable_PoC/github_retail_ecommerce_repositories.xlsx'
    
    # Language data mapping
    languages = {
        'Python': PYTHON_REPOS,
        'JavaScript': JAVASCRIPT_REPOS,
        'TypeScript': TYPESCRIPT_REPOS,
        'Java': JAVA_REPOS,
        'C#': CSHARP_REPOS,
    }
    
    # LoC range labels
    loc_ranges = ['1000', '3000', '5000', '7000', '10000']
    
    with xlsxwriter.Workbook(output_path, {'constant_memory': True}) as workbook:
        # Define formats
        header_format = workbook.add_format({
            'font_name': 'Arial',
            'font_size': 14,
            'bold': True,
            'bg_color': '#4472C4',
            'font_color': 'white',
            'border': 1,
            'align': 'left',
            'valign': 'vcenter',
        })
        
        cell_format = workbook.add_format({
            'font_name': 'Arial',
            'font_size': 12,
            'border': 1,
            'align': 'left',
            'valign': 'vcenter',
            'text_wrap': True,
        })
        
        url_format = workbook.add_format({
            'font_name': 'Arial',
            'font_size': 12,
            'border': 1,
            'font_color': 'blue',
            'underline': 1,
            'valign': 'vcenter',
        })
        
        loc_format = workbook.add_format({
            'font_name': 'Arial',
            'font_size': 12,
            'border': 1,
            'align': 'right',
            'valign': 'vcenter',
        })
        
        for lang_name, lang_data in languages.items():
            # Create worksheet for each language
            worksheet = workbook.add_worksheet(lang_name)
            
            # Set column widths
            worksheet.set_column('A:A', 6)   # S.No
            worksheet.set_column('B:B', 30)  # Repository Name
            worksheet.set_column('C:C', 50)  # URL
            worksheet.set_column('D:D', 40)  # Description
            worksheet.set_column('E:E', 35)  # Key Features
            worksheet.set_column('F:F', 15)  # Estimated LoC
            
            # Write headers
            headers = ['S.No', 'Repository Name', 'URL', 'Description', 'Key Features', 'Estimated LoC']
            for col, header in enumerate(headers):
                worksheet.write(0, col, header, header_format)
            
            row = 1
            s_no = 1
            
            # Write data for each LoC range
            for loc_range in loc_ranges:
                repos = lang_data.get(loc_range, [])
                for repo in repos:
                    name, url, description, features, loc = repo
                    
                    worksheet.write(row, 0, s_no, cell_format)
                    worksheet.write(row, 1, name, cell_format)
                    worksheet.write_url(row, 2, url, url_format, string=url)
                    worksheet.write(row, 3, description, cell_format)
                    worksheet.write(row, 4, features, cell_format)
                    worksheet.write(row, 5, loc, loc_format)
                    
                    row += 1
                    s_no += 1
            
            # Add freeze panes
            worksheet.freeze_panes(1, 0)
    
    print(f"Excel file created successfully: {output_path}")
    print(f"Total repositories: {sum(len(repos) for lang in languages.values() for repos in lang.values())}")
    return output_path

if __name__ == '__main__':
    create_excel_file()
